language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python3 -m spacy download de_core_news_sm
# command to run tests
script:
  - pytest
